export enum EventCategory {
  LiveMusic = 'live_music',
  ClubNight = 'club_night',
  Comedy = 'comedy',
  Theatre = 'theatre',
  ArtsExhibition = 'arts_exhibition',
  Workshop = 'workshop',
  TalkLecture = 'talk_lecture',
  Film = 'film',
  Family = 'family',
  Sport = 'sport',
  CommunityMeetup = 'community_meetup',
  FoodDrink = 'food_drink',
  Other = 'other',
}
